name: Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GO_VERSION: '>=1.27.0'
  TASK_VERSION: 3.x

jobs:
  readme:
    name: 📝 Generate README
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: arduino/setup-task@v3
        with:
          version: ${{ env.TASK_VERSION }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Render README.md
        run: task docs:readme

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update README.md"
          file_pattern: README.md
